apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server-nodeport
  namespace: argocd
spec:
  clusterIP: 10.43.105.164
  clusterIPs:
  - 10.43.105.164
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30008 
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30009
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
