apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kube-prom
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.3.8
    helm.sh/chart: grafana-6.51.5
  name: kube-prom-v1-grafana-np
  namespace: kube-prom
spec:
  clusterIP: 10.43.121.56
  clusterIPs:
  - 10.43.121.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30010
  selector:
    app.kubernetes.io/instance: kube-prom-1
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
